version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # onde está o requirements.txt
    schedule:
      interval: "daily" # pode ser daily, weekly ou monthly
    open-pull-requests-limit: 5
    
